export const serviceCategories = [
  "Beautician",
  "Hourly Housekeeper",
  "Nurse",
  "Caregiver",
  "AC Repair",
  "Electrician",
  "Plumber",
  "Mechanic",
  "Carpenter",
  "Painter",
  "Cleaner",
  "Home Tutor",
  "Computer Repair",
  "Appliance Repair",
  "Gardener",
  "Pest Control",
  "Security Guard",
  "Moving Service",
  "Laundry Service",
  "Cooking Service",
];